### PR TITLE
Fix filepath printing (fix #294)

### LINKED ISSUE #294: Path resolution
There seem to be a recurring malfunction: paths are (always?) prepended with `./`, even when they should not. For instance, assume we have three files,

### `D/unit.dk`

```
Unit: Type.
unit: Unit.
```

### `D/unitLib.dk`

```
#REQUIRE unit.
id : unit.Unit -> unit.Unit.
```

### `foo.dk`

```
#REQUIRE unit.
#REQUIRE unitLib.
def bar := unitLib.id unit.unit.
```

## Symptom 1: `dk dep`

Dependency computation returns a not-so-correct output:
```sh
$ cd D
$ dk dep *.dk
./unit.dko : unit.dk
./unitLib.dko : unitLib.dk ./unit.dko
```
With these dependencies, `make unitLib.dko` just does not work (I assume it's because `unitLib.dko` is not the same as `./unitLib.dko` for make).

## Symptom 2: `dk check`

Assuming `D/unit.dko` and `D/unitLib.dko` have been created, the command
```sh
$ dk check -I D/ foo.dk
[SUCCESS] foo.dk was successfully checked.
```
works, *but*
```sh
$ dk check -I "$(realpath D)" foo.dk
[ERROR CODE:902] ...
No object file (.dko) found for module unit located at .//[...]/D/unit.dko
```

### PR DESCRIPTION
**Pull request by gabrielhdt**

### CODE REVIEW

File: api/files.ml [hunk 1]
```diff
@@ -47,8 +47,9 @@ let rec file_status load_path md candidates =
 
 let file_status load_path md = file_status load_path md []
 
-let as_object_file ?(prefix = Filename.current_dir_name) (File file) =
-  File (Filename.concat prefix (Filename.chop_extension file ^ "." ^ "dko"))
+let as_object_file ?prefix (File file) =
+  let suffix = Filename.chop_extension file ^ ".dko" in
+  File (match prefix with None -> suffix | Some p -> Filename.concat p suffix)
```
Comment (francoisthire) [inline api/files.ml:52]: `suffix` is actually a filename so I suggest:

```ocaml
  let basename = Filename.chop_extension file ^ ".dko" in
  File (match prefix with None -> suffix | Some p -> Filename.concat p basename)
```

and even better IMHO:

```ocaml
  let basename = Filename.chop_extension file ^ ".dko" in
  let filename = match prefix with None -> sufix | Some path -> Filename.concat path basename in
  File filename
```
